name: Syntax Check

# Run the deployment only when code is committed to the branch.
on:
  pull_request:
    branches:
      - master
      - next-release
      - setup-phpstan

jobs:
  lint-and-audit:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [7.4, 8.0]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.node }}
        coverage: none
        tools: composer

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Configure Composer cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: PHP Syntax Errors
      run: if find . -name "*.php" ! -path "./vendor/*" ! -path "./admin/bsf-core/*" -exec php -l {} \; | grep "Errors parsing"; then exit 1; fi
